export type G_PN = `${string}_PN`;
export type G_N = `${string}_N`;
export type G_N2 = `${string}_N2`;
export type G_N3 = `${string}_N3`;
export type G_A = `${string}_A`;
export type G_AV = `${string}_AV`;
export type G_A2 = `${string}_A2`;
export type G_A2V = `${string}_A2V`;
export type G_V0 = `${string}_V0`;
export type G_V = `${string}_V` | G_V0;
export type G_VA = `${string}_VA`;
export type G_VS = `${string}_VS`;
export type G_VQ = `${string}_VQ`;
export type G_V2 = `${string}_V2`;
export type G_V2S = `${string}_V2S`;
export type G_V2Q = `${string}_V2Q`;
export type G_V2V = `${string}_V2V`;
export type G_V3 = `${string}_V3`;
export type G_Interj = `${string}_Interj`;

export default {
	N: new Map<string, G_N>([
		['raı', 'fish_N'], // hack: no "thing_N" in gf-rgl? ;_;
		['seoqmeaq', 'airplane_N'],
		['rıochao', 'airplane_N'],
		['kuabue', 'apartment_N'],
		['shamu', 'apple_N'],
		['lea', 'art_N'],
		['be', 'baby_N'],
		['bebe', 'baby_N'],
		['bem', 'baby_N'],
		['bıra', 'beer_N'],
		['gusıoq', 'bike_N'],
		['shuao', 'bird_N'],
		['meaq', 'boat_N'],
		['kue', 'book_N'],
		['buchu', 'boot_N'],
		['joaq', 'boss_N'],
		['guaıjoaq', 'boss_N'],
		['naqdeo', 'boy_N'],
		['naqcıo', 'boy_N'],
		['noaısham', 'butter_N'],
		['nam', 'bread_N'],
		['fuaqkea', 'camera_N'],
		['shaqchea', 'cap_N'],
		['taqchao', 'car_N'],
		['chao', 'car_N'],
		['deaqfua', 'carpet_N'],
		['deaqfuq', 'carpet_N'],
		['kato', 'cat_N'],
		['gochıq', 'cat_N'],
		['gaodeaq', 'ceiling_N'],
		['tuıfua', 'chair_N'],
		['kuha', 'cheese_N'],
		['deo', 'child_N'],
		['jıaojıo', 'church_N'],
		['chıjıo', 'church_N'],
		['doaq', 'city_N'],
		['tıefuq', 'coat_N'],
		['ruqfuq', 'coat_N'],
		['jıoqkea', 'computer_N'],
		['koqpıuta', 'computer_N'],
		['daokea', 'computer_N'],
		['romkea', 'computer_N'],
		['gua', 'country_N'],
		['goıche', 'doctor_N'],
		['kune', 'dog_N'],
		['asu', 'dog_N'],
		['kıaotoq', 'door_N'],
		['paıgıq', 'enemy_N'],
		['shuaqjıo', 'factory_N'],
		['cıe', 'fish_N'],
		['deaq', 'floor_N'],
		['rua', 'flower_N'],
		['koakea', 'fridge_N'],
		['paı', 'friend_N'],
		['zeo', 'fruit_N'],
		['soaq', 'garden_N'],
		['lıqdeo', 'girl_N'],
		['lıqcıo', 'girl_N'],
		['muqfua', 'glove_N'],
		['eloa', 'gold_N'],
		['meaqce', 'harbour_N'],
		['chea', 'hat_N'],
		['meı', 'hill_N'],
		['eku', 'horse_N'],
		['kebo', 'horse_N'],
		['buajıo', 'house_N'],
		['shuaqjıaq', 'industry_N'],
		['ceke', 'iron_N'],
		['ruaınaq', 'king_N'],
		['guaqnao', 'lake_N'],
		['suroq', 'lake_N'],
		['gıokea', 'lamp_N'],
		['gıofua', 'lamp_N'],
		['poq', 'person_N'],
		['guobe', 'cow_N'],
	]),
	N2: new Map<string, G_N2>([
		['naqpıa', 'brother_N2'],
		['fıom', 'cousin_N2'],
		['naqpao', 'father_N2'],
	]),
	N3: new Map<string, G_N3>([['tıjaone', 'distance_N3']]),
	A: new Map<string, G_A>([
		['huı', 'bad_A'],
		['de', 'beautiful_A'],
		['kaqde', 'beautiful_A'],
		['nea', 'broad_A'],
		['sao', 'big_A'],
		['kuo', 'black_A'],
		['mıo', 'blue_A'],
		['tıaq', 'brown_A'],
		['sıq', 'clean_A'],
		['moıjoe', 'clever_A'],
		['koa', 'cold_A'],
		['geaq', 'dirty_A'],
		['heqshea', 'empty_A'],
		['gı', 'good_A'],
		['rıq', 'green_A'],
		['loq', 'hot_A'],
		['suao', 'important_A'],
	]),
	AV: new Map<string, G_AV>([['puagı', 'fun_AV']]),
	A2: new Map<string, G_A2>([['seo', 'married_A2']]),
	A2V: new Map<string, G_A2V>([['fuı', 'easy_A2V']]),
	V0: new Map<string, G_V0>([['ruqshua', 'rain_V0']]),
	V: new Map<string, G_V>([
		['aona', 'come_V'],
		['muaqsho', 'die_V'],
		['fa', 'go_V'],
		['nuo', 'sleep_V'],
		['koı', 'walk_V'],
	]),
	VA: new Map<string, G_VA>([['sho', 'become_VA']]),
	VS: new Map<string, G_VS>([
		['faqtea', 'fear_VS'],
		['lutea', 'fear_VS'],
		['zaı', 'hope_VS'],
		['dua', 'know_VS'],
		['ruaq', 'say_VS'],
	]),
	VQ: new Map<string, G_VQ>([['dua', 'know_VQ']]),
	V2: new Map<string, G_V2>([
		['poaqtua', 'break_V2'],
		['bojea', 'buy_V2'],
		['poatua', 'close_V2'],
		['pıe', 'drink_V2'],
		['chuq', 'eat_V2'],
		['geqtaı', 'find_V2'],
		['joaıtaı', 'find_V2'],
		['tıduasho', 'find_V2'],
		['heaqmeu', 'forget_V2'],
		['loı', 'hate_V2'],
		['huogaı', 'hear_V2'],
		['zao', 'know_V2'],
		['noaq', 'read_V2'],
		['kaqgaı', 'see_V2'],
	]),
	V2S: new Map<string, G_V2S>([['cuadeoq', 'answer_V2S']]),
	V2Q: new Map<string, G_V2Q>([['duasue', 'ask_V2Q']]),
	V2V: new Map<string, G_V2V>([['caısue', 'beg_V2V']]),
	V3: new Map<string, G_V3>([
		['do', 'give_V3'],
		['dıeq', 'send_V3'],
	]),
	PN: new Map<string, G_PN>([
		['parı', 'paris_PN'],
		['joq', 'john_PN'],
	]),
	Interj: new Map<string, G_Interj>([['ubaı', 'alas_Interj']]),
};
