export type G_PN = `${string}_PN`;
export type G_P = `${string}P`; // no underscore here, "aboutP" etc
export type G_N = `${string}_N`;
export type G_N2 = `${string}_N2`;
export type G_N3 = `${string}_N3`;
export type G_A = `${string}_A`;
export type G_AV = `${string}_AV`;
export type G_AS = `${string}_AS`;
export type G_A2 = `${string}_A2`;
export type G_A2V = `${string}_A2V`;
export type G_V0 = `${string}_V0`;
export type G_V = `${string}_V` | G_V0;
export type G_VA = `${string}_VA`;
export type G_VS = `${string}_VS`;
export type G_VQ = `${string}_VQ`;
export type G_V2 = `${string}_V2`;
export type G_V2A = `${string}_V2A`;
export type G_V2S = `${string}_V2S`;
export type G_V2Q = `${string}_V2Q`;
export type G_V2V = `${string}_V2V`;
export type G_V3 = `${string}_V3`;
export type G_Interj = `${string}_Interj`;

export default {
	N: new Map<string, G_N>([
		['raı', 'fish_N'], // hack: no "thing_N" in gf-rgl? ;_;
		['seoqmeaq', 'airplane_N'],
		['rıochao', 'airplane_N'],
		['kuabue', 'apartment_N'],
		['shamu', 'apple_N'],
		['lea', 'art_N'],
		['be', 'baby_N'],
		['bebe', 'baby_N'],
		['bem', 'baby_N'],
		['bıra', 'beer_N'],
		['gusıoq', 'bike_N'],
		['shuao', 'bird_N'],
		['meaq', 'boat_N'],
		['nuımeaq', 'boat_N'],
		['kue', 'book_N'],
		['buchu', 'boot_N'],
		['joaq', 'boss_N'],
		['guaıjoaq', 'boss_N'],
		['naqdeo', 'boy_N'],
		['naqcıo', 'boy_N'],
		['noaısham', 'butter_N'],
		['nam', 'bread_N'],
		['fuaqkea', 'camera_N'],
		['shaqchea', 'cap_N'],
		['taqchao', 'car_N'],
		['chao', 'car_N'],
		['deaqfua', 'carpet_N'],
		['deaqfuq', 'carpet_N'],
		['kato', 'cat_N'],
		['gochıq', 'cat_N'],
		['gaodeaq', 'ceiling_N'],
		['tuıfua', 'chair_N'],
		['kuha', 'cheese_N'],
		['deo', 'child_N'],
		['jıaojıo', 'church_N'],
		['chıjıo', 'church_N'],
		['doaq', 'city_N'],
		['tıefuq', 'coat_N'],
		['ruqfuq', 'coat_N'],
		['jıoqkea', 'computer_N'],
		['koqpıuta', 'computer_N'],
		['daokea', 'computer_N'],
		['romkea', 'computer_N'],
		['gua', 'country_N'],
		['guobe', 'cow_N'],
		['goıche', 'doctor_N'],
		['kune', 'dog_N'],
		['asu', 'dog_N'],
		['kıaotoq', 'door_N'],
		['paıgıq', 'enemy_N'],
		['shuaqjıo', 'factory_N'],
		['cıe', 'fish_N'],
		['deaq', 'floor_N'],
		['rua', 'flower_N'],
		['koakea', 'fridge_N'],
		['paı', 'friend_N'],
		['zeo', 'fruit_N'],
		['soaq', 'garden_N'],
		['lıqdeo', 'girl_N'],
		['lıqcıo', 'girl_N'],
		['muqfua', 'glove_N'],
		['eloa', 'gold_N'],
		['meaqce', 'harbour_N'],
		['chea', 'hat_N'],
		['meı', 'hill_N'],
		['eku', 'horse_N'],
		['kebo', 'horse_N'],
		['buajıo', 'house_N'],
		['shuaqjıaq', 'industry_N'],
		['ceke', 'iron_N'],
		['ruaınaq', 'king_N'],
		['guaqnao', 'lake_N'],
		['suroq', 'lake_N'],
		['gıokea', 'lamp_N'],
		['gıofua', 'lamp_N'],
		['puga', 'leather_N'],
		['maıse', 'love_N'],
		['naq', 'man_N'],
		['naqkoaq', 'man_N'],
		['nueq', 'meat_N'],
		['noaı', 'milk_N'],
		['mıao', 'moon_N'],
		['saomeı', 'mountain_N'],
		['gıaq', 'music_N'],
		['dıaqkue', 'newspaper_N'],
		['nıqkue', 'newspaper_N'],
		['nulı', 'oil_N'],
		['pıonulı', 'oil_N'],
		['luqse', 'peace_N'],
		['bolıa', 'pen_N'],
		['kaıchuo', 'pen_N'],
		['meaı', 'planet_N'],
		['pıanete', 'planet_N'],
		['hıle', 'plastic_N'],
		['ꝡachım', 'plastic_N'],
		['sıjuche', 'policeman_N'],
		['chıjoaq', 'priest_N'],
		['ruaıjoaq', 'queen_N'],
		['ruaılıq', 'queen_N'],
		['radıokea', 'radio_N'],
		['chıchuaq', 'religion_N'],
		['haqrıaq', 'restaurant_N'],
		['chuqrıaq', 'restaurant_N'],
		['hıu', 'river_N'],
		['pıo', 'rock_N'],
		['jıochea', 'roof_N'],
		['gola', 'rubber_N'],
		['hebesaı', 'rubber_N'],
		['chıejıo', 'school_N'],
		['sıomjıo', 'school_N'],
		['sıomrıaq', 'school_N'],
		['dıu', 'science_N'],
		['naomı', 'sea_N'],
		['saomeaq', 'ship_N'],
		['shatı', 'shirt_N'],
		['saka', 'shirt_N'],
		['puefuq', 'shoe_N'],
		['koıfuq', 'shoe_N'],
		['jearıaq', 'shop_N'],
		['dıem', 'shop_N'],
		['mıala', 'silver_N'],
		['lıqpıa', 'sister_N'],
		['oguı', 'snake_N'],
		['puetıe', 'sock_N'],
		['nuım', 'star_N'],
		['zoku', 'steel_N'],
		['pıo', 'stone_N'],
		['loefua', 'stove_N'],
		['chıeche', 'student_N'],
		['sıomche', 'student_N'],
		['hoe', 'sun_N'],
		['toqfua', 'table_N'],
		['galeche', 'teacher_N'],
		['tıbı', 'television_N'],
		['chue', 'train_N'],
		['chuechao', 'train_N'],
		['muao', 'tree_N'],
		['saochıe', 'university_N'],
		['doaq', 'village_N'],
		['luqdoaq', 'village_N'],
		['soıcheq', 'war_N'],
		['nao', 'water_N'],
		['chuao', 'window_N'],
		['seaı', 'wine_N'],
		['beıho', 'wine_N'],
		["beı'o", 'wine_N'],
		['lıq', 'woman_N'],
		['lıqkoaq', 'woman_N'],
		['koaqlıq', 'woman_N'],
		['muaosaı', 'wood_N'],
		['suaqse', 'song_N'],
		['suaqgıaq', 'song_N'],
		['zıu', 'number_N'],

		['nıaı', 'animal_N'],
		['ruka', 'back_N'],
		['muaopıu', 'bark_N'],
		['heoqshaq', 'belly_N'],
		['sıaı', 'blood_N'],
		['kuoq', 'bone_N'],
		['teaq', 'breast_N'],
		['puao', 'cloud_N'],
		['chaq', 'day_N'],
		['puo', 'dust_N'],
		['rıopuo', 'dust_N'],
		['kuapuo', 'dust_N'],
		['huohua', 'ear_N'],
		['moma', 'ear_N'],
		['asaı', 'earth_N'],
		['guaqsaı', 'earth_N'],
		['kubo', 'egg_N'],
		['poaı', 'egg_N'],
		['nıaıpoaı', 'egg_N'],
		['kaqhua', 'eye_N'],
		["ka'a", 'eye_N'],
		['kaꝡa', 'eye_N'],
		['adı', 'fat_N'],
		['hue', 'feather_N'],
		['ceaq', 'fingernail_N'],
		['loe', 'fire_N'],
		['rua', 'flower_N'],
		['nıapuao', 'fog_N'],
		['pue', 'foot_N'],
		['muaoguaq', 'forest_N'],
		['muaome', 'forest_N'],
		['poıba', 'grass_N'],
		['nıehua', 'guts_N'],
		['kıaq', 'hair_N'],
		['muq', 'hand_N'],
		['joqhua', 'head_N'],
		['mıehua', 'heart_N'],
		['moehua', 'heart_N'],
		['tuaq', 'horn_N'],
		['naqseo', 'husband_N'],
		['kıeı', 'ice_N'],
		['chuaınao', 'ice_N'],
		['shıaqbea', 'knee_N'],
		['nıuboe', 'leaf_N'],
		['shıaq', 'leg_N'],
		['hıeku', 'liver_N'],
		['jeku', 'liver_N'],
		['peteı', 'louse_N'],
		['pıuchıq', 'louse_N'],
		['buq', 'mouth_N'],
		['chua', 'name_N'],
		['boa', 'neck_N'],
		['nuaq', 'night_N'],
		['shıqhua', 'nose_N'],
		['poq', 'person_N'],
		['ruq', 'rain_N'],
		['tıeq', 'road_N'],
		['chaotıeq', 'road_N'],
		['aka', 'root_N'],
		['chuoı', 'rope_N'],
		['nhoq', 'rope_N'],
		['keaqsaı', 'salt_N'],
		['anı', 'sand_N'],
		['poaı', 'seed_N'],
		['pıu', 'skin_N'],
		['seoq', 'sky_N'],
		['goq', 'smoke_N'],
		['nıao', 'snow_N'],
		['beaq', 'stick_N'],
		['kahu', 'tail_N'],
		['huoı', 'tail_N'],
		['leq', 'tongue_N'],
		['nıoq', 'tooth_N'],
		['lıqseo', 'wife_N'],
		['ırue', 'wind_N'],
		['shoaı', 'wing_N'],
		['nuq', 'worm_N'],
		['nunuq', 'worm_N'],
		['nıaq', 'year_N'],
		['zujuaome', 'grammar_N'],
		['zu', 'language_N'],
		['juao', 'rule_N'],
		['teoq', 'question_N'],
		['kuıtue', 'reason_N'],
	]),
	N2: new Map<string, G_N2>([
		['naqpıa', 'brother_N2'],
		['fıom', 'cousin_N2'],
		['naqpao', 'father_N2'],
		['lıqpao', 'mother_N2'],
	]),
	N3: new Map<string, G_N3>([['tıjaone', 'distance_N3']]),
	A: new Map<string, G_A>([
		['huı', 'bad_A'],
		['de', 'beautiful_A'],
		['kaqde', 'beautiful_A'],
		['nea', 'broad_A'],
		['sao', 'big_A'],
		['kuo', 'black_A'],
		['mıo', 'blue_A'],
		['tıaq', 'brown_A'],
		['sıq', 'clean_A'],
		['moıjoe', 'clever_A'],
		['koa', 'cold_A'],
		['geaq', 'dirty_A'],
		['heqshea', 'empty_A'],
		['gı', 'good_A'],
		['rıq', 'green_A'],
		['loq', 'hot_A'],
		['suao', 'important_A'],
		['buaı', 'long_A'],
		['zuı', 'narrow_A'],
		['nıq', 'new_A'],
		['geo', 'old_A'],
		['kıa', 'red_A'],
		['doq', 'short_A'],
		['nui', 'small_A'],
		['moınıeq', 'stupid_A'],
		['moaı', 'thick_A'],
		['ruoı', 'thin_A'],
		['fıe', 'ugly_A'],
		['foaqloq', 'warm_A'],
		['bao', 'white_A'],
		['lue', 'yellow_A'],
		['nıo', 'young_A'],
		['due', 'correct_A'],
		['gıao', 'dry_A'],
		['foıge', 'dull_A'],
		['heqmuo', 'full_A'],
		['tuoq', 'heavy_A'],
		['tıjuı', 'near_A'],
		['peom', 'rotten_A'],
		['kıoq', 'rotten_A'],
		['moem', 'round_A'],
		['choı', 'sharp_A'],
		['goaq', 'smooth_A'],
		['ruoq', 'straight_A'],
		['cuaı', 'wet_A'],
		['nea', 'wide_A'],
		['buo', 'ready_A'],
		['legıq', 'uncertain_A'],
		['zam', 'uncertain_A'],
	]),
	AV: new Map<string, G_AV>([['puagı', 'fun_AV']]),
	AS: new Map<string, G_AS>([['le', 'probable_AS']]),
	A2: new Map<string, G_A2>([['seo', 'married_A2']]),
	A2V: new Map<string, G_A2V>([['fuı', 'easy_A2V']]),
	V0: new Map<string, G_V0>([['ruqshua', 'rain_V0']]),
	V: new Map<string, G_V>([
		['aona', 'come_V'],
		['muaqsho', 'die_V'],
		['fa', 'go_V'],
		['mıe', 'live_V'],
		['jara', 'run_V'],
		['nuo', 'sleep_V'],
		['saofa', 'travel_V'],
		['ramfa', 'travel_V'],
		['koı', 'walk_V'],
		['fashaı', 'stop_V'],
		['loma', 'jump_V'],

		['fuha', 'blow_V'],
		['ceu', 'breathe_V'],
		['loe', 'burn_V'],
		['guaqhuaı', 'dig_V'],
		['shua', 'fall_V'],
		['rıolıaı', 'float_V'],
		['loaı', 'flow_V'],
		['rıofa', 'fly_V'],
		['chuaısho', 'freeze_V'],
		['hıaı', 'laugh_V'],
		['reaq', 'lie_V'],
		['luaq', 'play_V'],
		['sorı', 'sew_V'],
		['suaq', 'sing_V'],
		['tuı', 'sit_V'],
		['shıqgaı', 'smell_V'],
		['cutao', 'spit_V'],
		['sheaq', 'stand_V'],
		['beqsho', 'swell_V'],
		['lıaı', 'swim_V'],
		['naolıaı', 'swim_V'],
		['moı', 'think_V'],
		['muoı', 'turn_V'],
		['haqcıu', 'vomit_V'],
	]),
	VA: new Map<string, G_VA>([['sho', 'become_VA']]),
	VS: new Map<string, G_VS>([
		['faqtea', 'fear_VS'],
		['lutea', 'fear_VS'],
		['zaı', 'hope_VS'],
		['dua', 'know_VS'],
		['ruaq', 'say_VS'],
	]),
	VQ: new Map<string, G_VQ>([
		['dua', 'know_VQ'],
		['duashao', 'wonder_VQ'],
		['ruıq', 'wonder_VQ'],
	]),
	V2: new Map<string, G_V2>([
		['poaqtua', 'break_V2'],
		['bojea', 'buy_V2'],
		['poatua', 'close_V2'],
		['pıe', 'drink_V2'],
		['chuq', 'eat_V2'],
		['geqtaı', 'find_V2'],
		['joaıtaı', 'find_V2'],
		['tıduasho', 'find_V2'],
		['heaqmeu', 'forget_V2'],
		['loı', 'hate_V2'],
		['huogaı', 'hear_V2'],
		['zao', 'know_V2'],
		['chıe', 'learn_V2'], // not VS... hm
		['tıshaı', 'leave_V2'],
		['cho', 'like_V2'],
		['huosı', 'listen_V2'],
		['paqshaı', 'lose_V2'],
		['heaqshaı', 'lose_V2'],
		['maı', 'love_V2'],
		['ano', 'love_V2'],
		['rıatua', 'open_V2'],
		['luaq', 'play_V2'],
		['gıaqchoq', 'play_V2'],
		['noaq', 'read_V2'],
		['joaı', 'seek_V2'],
		['kaqgaı', 'see_V2'],
		['choa', 'speak_V2'],
		['domja', 'switch8off_V2'],
		['atıja', 'switch8on_V2'],
		['gale', 'teach_V2'],
		['muodua', 'understand_V2'],
		['lım', 'understand_V2'],
		['lao', 'wait_V2'],
		['kaqsı', 'watch_V2'],
		['kaı', 'write_V2'],

		['kaqga', 'bite_V2'],
		['puımıeq', 'count_V2'],
		['toe', 'cut_V2'],
		['getea', 'fear_V2'],
		['soı', 'fight_V2'],
		['dea', 'hit_V2'],
		['heaq', 'hold_V2'],
		['juku', 'hunt_V2'],
		['muaqja', 'kill_V2'],
		['muaqtua', 'kill_V2'],
		['baga', 'pull_V2'],
		['hupa', 'push_V2'],
		['dem', 'push_V2'],
		['goaıfuoq', 'rub_V2'],
		['gıaı', 'scratch_V2'],
		['gutua', 'split_V2'],
		['bıpa', 'squeeze_V2'],
		['choıdea', 'stab_V2'],
		['supu', 'suck_V2'],
		['hıeq', 'throw_V2'],
		['nhoqcoeja', 'tie_V2'],
		['nhoqcoetua', 'tie_V2'],
		['sıqtua', 'wash_V2'],
		['sıqja', 'wash_V2'],
		['sıqgoaı', 'wipe_V2'],

		['tıtua', 'put_V2'],
	]),
	V2A: new Map<string, G_V2A>([['reodo', 'paint_V2A']]),
	V2S: new Map<string, G_V2S>([['cuadeoq', 'answer_V2S']]),
	V2Q: new Map<string, G_V2Q>([['duasue', 'ask_V2Q']]),
	V2V: new Map<string, G_V2V>([['caısue', 'beg_V2V']]),
	V3: new Map<string, G_V3>([
		['do', 'give_V3'],
		['dıeq', 'send_V3'],
		['teqdo', 'sell_V3'],
		['keoı', 'talk_V3'],
		['raqkeoı', 'talk_V3'],
	]),
	PN: new Map<string, G_PN>([
		['parı', 'paris_PN'],
		['joq', 'john_PN'],
	]),
	P: new Map<string, G_P>([
		['raq', 'aboutP'],
		['tı', 'atP'],
		['nhuo', 'forP'],
		['sına', 'fromP'],
		['nıe', 'inP'],
		['neo', 'onP'],
		['fana', 'toP'],
	]),

	Interj: new Map<string, G_Interj>([['ubaı', 'alas_Interj']]),
};
