import { expect, test } from 'vitest';
import { parse } from '../modes/parse';
import { recover } from '../syntax/recover';
import { toScene } from './scene';

test('it turns trees into scenes', () => {
	const tree = parse('hao jí')[0];
	const denoted = recover(tree);
	expect(toScene(denoted, true, ['VP'])).toMatchInlineSnapshot(`
		{
		  "arrows": [
		    {
		      "from": 2,
		      "to": 3,
		    },
		    {
		      "from": 1,
		      "to": 2,
		    },
		  ],
		  "root": {
		    "children": [
		      {
		        "children": [
		          {
		            "children": [],
		            "denotation": undefined,
		            "gloss": undefined,
		            "id": undefined,
		            "label": "C",
		            "placement": undefined,
		            "roof": false,
		            "source": "",
		            "text": "∅",
		            "textStyle": 0,
		          },
		          {
		            "children": [
		              {
		                "children": [],
		                "denotation": undefined,
		                "gloss": undefined,
		                "id": undefined,
		                "label": "Σ",
		                "placement": undefined,
		                "roof": false,
		                "source": "",
		                "text": "∅",
		                "textStyle": 0,
		              },
		              {
		                "children": [
		                  {
		                    "children": [],
		                    "denotation": undefined,
		                    "gloss": undefined,
		                    "id": 3,
		                    "label": "T",
		                    "placement": undefined,
		                    "roof": false,
		                    "source": "",
		                    "text": "hao",
		                    "textStyle": 1,
		                  },
		                  {
		                    "children": [
		                      {
		                        "children": [],
		                        "denotation": undefined,
		                        "gloss": undefined,
		                        "id": 2,
		                        "label": "Asp",
		                        "placement": undefined,
		                        "roof": false,
		                        "source": "",
		                        "text": "∅",
		                        "textStyle": 2,
		                      },
		                      {
		                        "children": [
		                          {
		                            "children": [],
		                            "denotation": undefined,
		                            "gloss": undefined,
		                            "id": 1,
		                            "label": "𝘷",
		                            "placement": undefined,
		                            "roof": false,
		                            "source": "",
		                            "text": "BE",
		                            "textStyle": 2,
		                          },
		                          {
		                            "children": [],
		                            "denotation": undefined,
		                            "gloss": undefined,
		                            "id": undefined,
		                            "label": "VP",
		                            "placement": undefined,
		                            "roof": true,
		                            "source": "hao jí",
		                            "text": "hao jí",
		                            "textStyle": 0,
		                          },
		                        ],
		                        "denotation": undefined,
		                        "gloss": undefined,
		                        "id": undefined,
		                        "label": "𝘷P",
		                        "placement": undefined,
		                        "roof": false,
		                        "source": "hao jí",
		                        "text": undefined,
		                        "textStyle": 0,
		                      },
		                    ],
		                    "denotation": undefined,
		                    "gloss": undefined,
		                    "id": undefined,
		                    "label": "AspP",
		                    "placement": undefined,
		                    "roof": false,
		                    "source": "hao jí",
		                    "text": undefined,
		                    "textStyle": 0,
		                  },
		                ],
		                "denotation": undefined,
		                "gloss": undefined,
		                "id": undefined,
		                "label": "TP",
		                "placement": undefined,
		                "roof": false,
		                "source": "hao jí",
		                "text": undefined,
		                "textStyle": 0,
		              },
		            ],
		            "denotation": undefined,
		            "gloss": undefined,
		            "id": undefined,
		            "label": "ΣP",
		            "placement": undefined,
		            "roof": false,
		            "source": "hao jí",
		            "text": undefined,
		            "textStyle": 0,
		          },
		        ],
		        "denotation": undefined,
		        "gloss": undefined,
		        "id": undefined,
		        "label": "CP",
		        "placement": undefined,
		        "roof": false,
		        "source": "hao jí",
		        "text": undefined,
		        "textStyle": 0,
		      },
		      {
		        "children": [],
		        "denotation": undefined,
		        "gloss": undefined,
		        "id": undefined,
		        "label": "SA",
		        "placement": undefined,
		        "roof": false,
		        "source": "",
		        "text": "∅",
		        "textStyle": 0,
		      },
		    ],
		    "denotation": undefined,
		    "gloss": undefined,
		    "id": undefined,
		    "label": "SAP",
		    "placement": undefined,
		    "roof": false,
		    "source": "hao jí",
		    "text": undefined,
		    "textStyle": 0,
		  },
		}
	`);
});
